language: ruby
rvm:
  - 2.3.0
dist: xenial
services:
  - xvfb
before_install:
  - sudo add-apt-repository ppa:jonathonf/vim -y
  - sudo apt update
  - sudo apt install vim-gtk3
  - sudo apt install exuberant-ctags
before_script:
  - which vim
  - vim --version
  - ctags --version
  - cat Gemfile.lock
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
